spring.application.name=mod2

# H2 Database
spring.datasource.url=jdbc:h2:file:./db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=AnkitDB
spring.datasource.password=Ankit@123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
management.endpoints.web.exposure.include=*